#!/bin/bash

parentpath=/Users/kartiknagar/PostDoc/Z3/formulas/CRDT
z3=/Users/kartiknagar/PostDoc/Z3/z3-master/build/z3

run()
{
  crdt=$1
  consistencypolicy=$2
  dash="_"
  #base="$parent_path/$crdt/$crdt$dash$consistencypolicy$dashbase.smt"
  base=$parentpath
  base+=/$crdt/
  base+=$crdt
  base+=$dash
  base+=$consistencypolicy
  base+=$dash
  inductive=$base
  inductive+="inductive.smt"
  base+="base.smt"
  if $z3 -smt2 $base > out.txt; then
    echo "$crdt fails NON-INTERF-1 under $consistencypolicy"
  else
    if $z3 -smt2 $inductive > out.txt; then
      echo "$crdt fails NON-INTERF-2 under $consistencypolicy"
    else
      echo "$crdt converges under $consistencypolicy"
    fi
  fi
}

run Set EC
run Set CC
run Set PSI+RB
run Set PSI
#output=$(/Users/kartiknagar/PostDoc/Z3/z3-master/build/z3 -smt2 /Users/kartiknagar/PostDoc/Z3/formulas/CRDT/Set/simpleset_EC_base.smt)
