#!/bin/bash
#sysinfo_page

title="System Information for"
cat <<- _EOF_
    <html>
      <head>
        <title>
        $title $HOSTNAME
        </title
      </head>
      <body>
        <h1>$title $HOSTNAME</h1>
      </body>
    </html>
_EOF_
